name: Build Release APK

on:
  push:
    branches: [ "main" ] # या तुम्हारी जो ब्रांच हो (जैसे master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # या तुम्हारा जो फ्लटर वर्शन हो
          channel: 'stable'
          cache: true

      - name: Clean and Fix Project Android Structure
        run: |
          flutter clean
          flutter pub get
          flutter create . --platforms=android

      - name: Build Release APK
        run: flutter build apk --release --verbose

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
